In [8]:
# 2025.11.21 경주님꺼 함수 적용 수정 적용 전

import os
import sys

# 현재 작업 디렉토리 기준으로 상위 1단계 폴더를 루트로 설정
current_dir = os.getcwd()
project_root = os.path.abspath(os.path.join(current_dir, '..'))

# sys.path에 추가 (모듈 import용)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# print("프로젝트 루트로 설정된 경로:", project_root)

In [9]:
# 데이터 확인하기 2025.11.21 zero_count_rate > 95% 이상인 컬럼 제거 후 RandomForest 기본 모델 돌리기
import pandas as pd
import numpy  as np

from sklearn.preprocessing import StandardScaler # 데이터 전처리용

import matplotlib.pyplot as plt
import seaborn as sns

import importlib
from utils import preprocessing, user_utils

# 모듈 reload
importlib.reload(preprocessing)
importlib.reload(user_utils)

from utils.preprocessing import load_data, split_features_target, scale_data, data_split, remove_zero_columns
from utils.user_utils    import get_model_train_eval

In [10]:
# 데이터 로딩
train, test = load_data()

In [11]:
# 데이터 할당
X_features, y_labels = split_features_target(train) # ID와 TARGET 모두 제거하고 X_train 만들기
X_test     = test.drop(columns=['ID'], axis=1) # test 데이터에서도 ID 제거 

In [12]:
# Data 전처리 1. zero_count_rate이 99%인 컬럼 제거하기 
removed_train_df = remove_zero_columns(train, 0.99)


Zero Value Analysis (Threshold: 99.0% = 75,259 rows)
Total rows: 76,020
Total columns: 371

                                     Summary 정보 (zero_count 내림차순)                                     
                   ColumnName  na_Sum  nUnique          mode  modeFreq modeFreqRate  zero_count zero_count_rate
    imp_trasp_var17_out_hace3       0        1      0.000000     76020      100.00%       76020         100.00%
    imp_trasp_var33_out_hace3       0        1      0.000000     76020      100.00%       76020         100.00%
        imp_reemb_var33_hace3       0        1      0.000000     76020      100.00%       76020         100.00%
        imp_reemb_var13_hace3       0        1      0.000000     76020      100.00%       76020         100.00%
                   ind_var2_0       0        1      0.000000     76020      100.00%       76020         100.00%
                  ind_var27_0       0        1      0.000000     76020      100.00%       76020         100.00%
                    

In [13]:
# TEST Data 전처리 1. zero_count_rate이 95%인 컬럼 제거하기 
remove_zero_columns(test, 0.99)


Zero Value Analysis (Threshold: 99.0% = 75,059 rows)
Total rows: 75,818
Total columns: 370

                                     Summary 정보 (zero_count 내림차순)                                     
                   ColumnName  na_Sum  nUnique          mode  modeFreq modeFreqRate  zero_count zero_count_rate
saldo_medio_var13_medio_hace3       0        1      0.000000     75818      100.00%       75818         100.00%
                     ind_var2       0        1      0.000000     75818      100.00%       75818         100.00%
              saldo_var2_ult1       0        1      0.000000     75818      100.00%       75818         100.00%
                   ind_var2_0       0        1      0.000000     75818      100.00%       75818         100.00%
        num_reemb_var17_hace3       0        1      0.000000     75818      100.00%       75818         100.00%
        num_reemb_var13_hace3       0        1      0.000000     75818      100.00%       75818         100.00%
         num_reemb_v

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var41_comer_ult1,imp_op_var41_comer_ult3,imp_op_var41_efect_ult1,imp_op_var41_efect_ult3,...,saldo_medio_var8_ult3,saldo_medio_var12_hace2,saldo_medio_var12_hace3,saldo_medio_var12_ult1,saldo_medio_var12_ult3,saldo_medio_var13_corto_hace2,saldo_medio_var13_corto_hace3,saldo_medio_var13_corto_ult1,saldo_medio_var13_corto_ult3,var38
0,2,2,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40532.100000
1,5,2,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45486.720000
2,6,2,23,0.0,0.0,0.0,0.0,0.0,60.0,60.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46993.950000
3,7,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,187898.610000
4,9,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,73649.730000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75813,151831,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40243.200000
75814,151832,2,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,146961.300000
75815,151833,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,167299.770000
75816,151834,2,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016


In [14]:
# Data 전처리 2. var3 의 최소값 -99999 를 최빈값으로 변경하기
X_features['var3'] = X_features['var3'].replace(-999999, 2)

In [15]:
# 스케일링
X_train_scaled, X_test_scaled, scaler = scale_data(X_features, X_test)

In [16]:
# 학습/테스트 데이터 분리

X_train, X_val, y_train, y_val = data_split(
  X_features, 
  y_labels,
)

In [ ]:
# 1. XGBoost, 99%

# 99% 와 동일한 하이퍼파라미터 적용
from xgboost import XGBClassifier

# 모델 이름 생성
model_name = 'XGBoost_99per_basic'

xgb = XGBClassifier(
    n_estimators=500,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=23
)

# 함수 이용
get_model_train_eval(xgb, model_name, X_train, X_val, y_train, y_val)

# 99% 경주님꺼 함수적용 수정 전
# AUC: 0.8417, 정확도: 0.9606, 정밀도: 0.6667, 재현율: 0.0100, F1: 0.0196
# 오차행렬:
# [[14599     3]
#  [  596     6]]

✓ 모델 저장 완료: models\XGBoost_95per_basic.pkl
  파일 크기: 1.46 MB
folder = c:\big20\git\big20-ML-project2-team3\SantanderCS\results
AUC: 0.8418, 정확도: 0.9603, 정밀도: 0.4000, 재현율: 0.0066, F1: 0.0131
오차행렬:
[[14596     6]
 [  598     4]]
실행 시간: 6.628321409225464


In [ ]:
# 2. LogisticRegression 99%

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score

# 모델 이름 생성
model_name = 'LogisticRegression_99per_basic'

log_reg = LogisticRegression(
    max_iter=1000,        # 반복 횟수 충분히 크게
    solver='lbfgs',       # 최적화 알고리즘
    random_state=42,
    n_jobs=-1
)

# 함수 이용
get_model_train_eval(log_reg, model_name, X_train, X_val, y_train, y_val)

# 99% 경주님꺼 함수적용 수정 전
# Accuracy: 0.9606024730334123
# ROC-AUC: 0.841652897864535

# AUC: 0.6216, 정확도: 0.9603, 정밀도: 0.0000, 재현율: 0.0000, F1: 0.0000
# 오차행렬:
# [[14600     2]
#  [  602     0]]

✓ 모델 저장 완료: models\LogisticRegression_99per_basic.pkl
  파일 크기: 0.01 MB
folder = c:\big20\git\big20-ML-project2-team3\SantanderCS\results
AUC: 0.6216, 정확도: 0.9603, 정밀도: 0.0000, 재현율: 0.0000, F1: 0.0000
오차행렬:
[[14600     2]
 [  602     0]]
실행 시간: 31.60127592086792
